### ISSUE TITLE
Mouseup outside img when panning / zooming should not deactivate

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#23]
Any mouseup events that occur outside `simpla-img` will deactivate it, this means that if you're panning / zooming and release the mouse after it's left the img, it will deactivate and all the controls will be hidden.

It should instead check to see if mousedown occurred inside `simpla-img` before mouseup to check if it started within `simpla-img`, and not deactivate if that's the case.

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-img/releases/tag/v1.0.0
