### ISSUE TITLE
Uploading image with same name as previous upload doesn't work

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-img#29]
**Expected behaviour:** Every time I upload an image my previous image gets replaced, regardless of filename or attributes

**IRL:** If uploaded image has same filename as current image, the current image does not get replaced

**Comment by bedeoverend** [comment]
It looks like the file input gets loaded with the image and stores a fake filepath. Re-uploading of the same name will result in the same filepath so it doesn't think anything's changed. Resolution to this will be just scrapping the value of input once the image has been uploaded and rendered into the image.

e.g. ```js
fileInput.value = '';
```

**Comment by seaneking** [comment]
@bedeoverend still an issue in 1.0?

**Comment by bedeoverend** [comment]
@seaneking yeah pretty sure it is - I think what should be needed here is clearing the File Input after each upload e.g. `this.$.fileInput.value = null`. Otherwise it doesn't think its "changed" on the next upgrade
