### ISSUE TITLE
Changing UID to point to empty content should clear current content

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#30]
When changing the UID (whether via it's SID or block's UID), it will fetch content at the new UID, but if that content is empty, it retains the current value, rather than clearing it.

It looks like it's [this line here](https://github.com/SimplaElements/simpla-img/blob/master/src/simpla-img/behaviors/default.js#L42), as when there is no default, it doesn't set `this.src`. Simple solution would be to just use an empty string if _default is falsey.

Same problem as https://github.com/SimplaElements/simpla-text/issues/22

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/simpla-img/releases/tag/v1.0.0
