### ISSUE TITLE
Touch scrolling broken on some Android browsers

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#34]
Looks like Polymer adds `touch-action: none;` to any element with a `pan` listener event. This means that the `img` inside canvas gets the `touch-action:none` applied. On mobile Safari this works fine, but Chrome based ones stops any scroll from happening: replicate by opening up Chrome's device debugger and try simulate scrolling via touch events.

Track events need to be added declaratively, and I don't believe there's a way to dynamically add / remove the listener, the best way is most likely to add a `touch-action: auto !important;` when _not_ editable.

cc @seaneking

**Comment by seaneking** [comment]
Polymer eats your CSS, so I imagine you'd have to apply that `!important` declaratively, which is a bit messy. 

Surely there's _some_ way to add/remove listeners on the fly with Polymer? Can we attach a listener manually when entering edit mode, rather than on element initialisation?

**Comment by bedeoverend** [comment]
`on-track` is unique. Polymer only sets up the event to be fired when added declaratively, unfortunately not like your average `on-click` or similar. Looks like you may be able to [manually override](https://www.polymer-project.org/1.0/docs/devguide/gesture-events) using `setScrollDirection`, will try that and see how it goes.
