### ISSUE TITLE
[v1] Placeholder vanishes when filepicker opened, causing page reflows

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-img#46]
When the filepicker is opened the placeholder vanishes, causing images without an explicit height (read: most images) to go height 0 and cause the page to reflow/jump about

**Comment by bedeoverend** [comment]
Thanks to #48, this is now a visual bug, but not breaking - just looks a bit ugly while opening the filepicker, as the empty editor is visible

**Comment by seaneking** [comment]
Closing in favor of #50
