### ISSUE TITLE
Editor should float on top

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#58]
The editor is getting `z-index` of `auto`, but it should really be floating on top to make sure it's always visible / usable. 

@seaneking I think all that's happening here is missing a line in the `:host` [styles](https://github.com/SimplaElements/simpla-img/blob/master/src/simpla-img-editor.html#L27), should have a line `z-index: var(--simpla-on-top);`?

**Comment by seaneking** [comment]
Derp. Yep

**Comment by bedeoverend** [comment]
Fixed in 4eaeaa8abd12f616299e338775fd331ef07dbbb5
