### ISSUE TITLE
Uploaded images are missing file extension

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/simpla-img#66]
Images uploaded by simpla-img (converted from base64) are missing a file extension when they're pulled back in as the img src. This breaks a lot of common browser behavior, eg:
 - No contextual menu items like 'open image in new tab' or 'copy image'
- Downloading results in unknown filetype that can't be viewed unless you add appropriate extension

I imagine this should be a quick API patch? Just read the base64 type when we convert it to a blob and add the appropriate file extension to the filename.

**Comment by bedeoverend** [comment]
Yup should be a relatively small fix. I think also mimetype might be missing? Anyway, I'll flag it on the API and close this once fixed upstream.

**Comment by bedeoverend** [comment]
Closed upstream in the API
